folder:
  environment: unity_environments
  plot: plots
  models: tmp
extras:
  description: base
seed: 42
wandb:
  proj: proj
  name: name
  entity: entity
train:
  save_frequency: 100
  fast_forward: 20
  episodes: 5000000
  train_interval: 50
environment:
  name: RL_Simulator_5min_random
  no_graphics: True
  action_dim: 4
  state_dim: 50
  action_range: 1
hparams:
  batch_size: 512
  hidden_dim: 128
  reward_scale: 20
  replay_buffer_size: 1000000
  alpha: 0.0001
  explore_noise_scale: 0.5
  policy_target_update_interval: 3
  eval_noise_scale: 0.5
eval:
  deterministic: True